
import { useState } from "react";
import { X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";

interface AiAnalysisSidebarProps {
  isOpen: boolean;
  onClose: () => void;
  interviewData: {
    company: string;
    position: string;
    experience: string;
  };
}

interface PracticeQuiz {
  id: number;
  title: string;
  description: string;
}

// Temporary mock quizzes - will be generated by AI later
const mockQuizzes: PracticeQuiz[] = [
  {
    id: 1,
    title: "React Hooks Deep Dive",
    description: "Test your knowledge of React hooks and state management",
  },
  {
    id: 2,
    title: "System Design Basics",
    description: "Practice fundamental system design concepts",
  },
];

const AiAnalysisSidebar = ({ isOpen, onClose, interviewData }: AiAnalysisSidebarProps) => {
  const [selectedQuiz, setSelectedQuiz] = useState<PracticeQuiz | null>(null);

  const handleQuizClick = (quiz: PracticeQuiz) => {
    setSelectedQuiz(quiz);
    // In the future, this will navigate to the quiz page or open a modal
    alert(`Opening quiz: ${quiz.title}`);
  };

  return (
    <div
      className={`fixed right-0 top-0 h-full w-96 bg-white shadow-xl transform transition-transform duration-300 ease-in-out z-50 ${
        isOpen ? "translate-x-0" : "translate-x-full"
      }`}
    >
      <div className="p-6 h-full flex flex-col">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-xl font-semibold">AI Analysis</h2>
          <Button variant="ghost" size="icon" onClick={onClose}>
            <X className="h-4 w-4" />
          </Button>
        </div>

        <div className="space-y-6 flex-1 overflow-y-auto">
          <section>
            <h3 className="font-medium mb-3">Related Resources</h3>
            <ul className="space-y-2">
              <li>
                <a
                  href="#"
                  className="text-primary hover:underline block"
                >
                  LeetCode: System Design Questions
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="text-primary hover:underline block"
                >
                  React Documentation: Hooks Guide
                </a>
              </li>
            </ul>
          </section>

          <Separator />

          <section>
            <h3 className="font-medium mb-3">Practice Quizzes</h3>
            <div className="space-y-3">
              {mockQuizzes.map((quiz) => (
                <div
                  key={quiz.id}
                  className="p-3 border rounded-lg hover:bg-gray-50 cursor-pointer transition-colors"
                  onClick={() => handleQuizClick(quiz)}
                >
                  <h4 className="font-medium">{quiz.title}</h4>
                  <p className="text-sm text-muted-foreground">
                    {quiz.description}
                  </p>
                </div>
              ))}
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};

export default AiAnalysisSidebar;
